---
title: "FinalProject"
author: "Dikai Tang"
date: "11/5/2019"
output: html_document
---

### 0, misc
```{R warning = False, message = F, error = F}
library(DT)
library(rvest)
library(data.table)
library(tidyverse)
library(ggplot2)
library(caret)
library(mda)
library(e1071)
library(VGAM)
library(kernlab)
library(randomForest)
suppressMessages(library(leaps))
set.seed(1)
```

### 1. Score Functions, D
``` {R} 
modeScore <- function(result, ref){ #result n x 3, ref n x 1
  generalScore <- 0
  genreScore <- hash()
  
  for(i in 1:nrow(ref)) {
    if (result[i,1] == ref[i,]){
      score <- 100
      genreScore[ref[i,]] <- genreScore[ref[i,]] + 1
    } else if (result[i,2] == ref[i,]) {
      score <- 100
      genreScore[ref[i,]] <- genreScore[ref[i,]] + 1
    }else if (result[i,3] == ref[i,]) {
      score <- 100
      genreScore[ref[i,]] <- genreScore[ref[i,]] + 1
    }else {
      score <- 0
    }
    generalScore = generalScore + score
  }
  generalScore = generalScore / nrow(ref)
}
```
## 2. Data Cleaning, 
```{R warning = F,message= F}
setwd("D:/onedrive/private/Study/CalPoly/courses/GSB524MachineLearning/assignments/FinalProject/")
data <- data.frame(read_csv("SpotifyFeatures.csv"))
colnames(data)
# 1.1 most popular
mostPopularByArtist <- data #%>% group_by(artist_name) %>% top_n(1, popularity) %>% data.frame() 
#mostPopularByArtist <- mostPopularByArtist[mostPopularByArtist$popularity > 30, ]
# 1.2 exclude a few 
mostPopularByArtist <- mostPopularByArtist[!grepl("World|Child|Anime", mostPopularByArtist$genre),]
# 1.3 merge rap & hip-hop
mostPopularByArtist$genre[mostPopularByArtist$genre == "Hip-Hop"] <- "Rap"
data2<-mostPopularByArtist %>%
  select(-c(track_id, time_signature, track_name, artist_name, mode, key, popularity))

```

## 3. Explore Plot, D
```{R}

ggplot(mostPopularByArtist, aes(x=loudness, colour=genre)) + geom_density()
ggplot(mostPopularByArtist, aes(x=energy, colour=genre)) + geom_density()
ggplot(mostPopularByArtist, aes(x=tempo, colour=genre)) + geom_density()
ggplot(mostPopularByArtist[mostPopularByArtist$genre %in% c("Pop","Movie","Classical"),], aes(x=loudness, colour=genre)) + geom_density()

```



## 4. Forward Regression model exploratory
Subset
```{r}
sample_data <- data2[sample(1:nrow(data2), 5000, replace=FALSE),]
sample_data<-na.omit(sample_data)
sample_data$genre<-factor(sample_data$genre)
nrow(sample_data)
```

```{r}
set.seed(1)
## 75% of the sample size
smp_size <- floor(0.75 * nrow(sample_data))
## set the seed to make your partition reproducible
train_ind <- sample(seq_len(nrow(sample_data)), size = smp_size)
train <- sample_data[train_ind, ]
test <- sample_data[-train_ind, ]
#forward regression
regfit.fwd <- regsubsets(genre~ ., data=train, nvmax=4, force.in=NULL,
                         method = "forward")
summary(regfit.fwd)
```



### 4.1 Random Forest Classifier 
```{r}
sd.rf<-randomForest(genre~., data=train, importance=TRUE)
importance(sd.rf, type=1)
importance(sd.rf, type=2)
```


```{r}
```

## 5. kNN, M

## 6. Known Model 2, M

## 7. New Model KSVM, M 
```{R}
trainVar <- c("genre","acousticness",
               "danceability","duration_ms","energy",
               "instrumentalness","liveness",
               "loudness","speechiness",
               "tempo","valence")

trainSample <- mostPopularByArtist[sample(1:nrow(mostPopularByArtist), 10000, replace=FALSE),]
tstSample <- mostPopularByArtist[sample(1:nrow(mostPopularByArtist), 1000, replace=FALSE), ]
#fit <- ksvm(genre ~ ., data = trainSample[,trainVar])
vote <- predict(fit, tstSample[,trainVar], type="votes")

predictKSVM <- data.table()
genreNames <- lev(fit)
for(i in 1:nrow(tstSample)){
  topVotes<- sort(vote[,i], index.return=TRUE, decreasing=TRUE)$ix[1:3]
  topGenre<- genreNames[topVotes]
  predictKSVM<- rbind(predictKSVM, t(topGenre), fill=TRUE) 
}
colnames(predictKSVM)[1:3] <- c("Genre 1", "Genre 2", "Genre 3")
resultKSVM <- cbind(predictKSVM, tstSample)
scoreKSVM <- modeScore(predictKSVM, data.table(tstSample[,1]))
```

